---
font: Lato
fontsize: 10pt
geometry: left=1in,right=1in,top=0.35in,bottom=0.6in
header-includes: \input{preamble.tex}
output:
  html_document:
  word_document: default
  pdf_document: default
sansfont: Lato
urlcolor: null
params:
  county: "Los Angeles"
  start_date: "2020-04-15"
---

\raggedright


```{r rmarkdown-setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(dev = "cairo_pdf")
options(knitr.kable.NA = "")
options(kableExtra.latex.load_packages = FALSE)

# Knit RMarkdown
library(knitr)

# Tables
library(kableExtra)

# Data Cleaning pipeline
library(tidyverse)
library(dplyr)
library(scales) # formatting numbers
library(arrow) # read parquets
library(zoo) # moving averages
library(reshape2)

# Plotting
library(ggplot2)
library(ggthemes)
library(plotly) #interactive charts

```


```{r import-data}

us_county<-read_parquet("../data/us-county-time-series.parquet", as_tibble = TRUE)
ca_hospitalizations<-read.csv("../data/ca-hospital-and-surge-capacity.csv")

YESTERDAY_DATE <- format(Sys.Date()-1,"%Y-%m-%d")
TWO_WEEKS_AGO <- format(Sys.Date()-15, "%Y-%m-%d")

# Chart parameters
NAVY<-"#0A4C6A"
MAROON<- "#F3324C"
LIGHT_GRAY<-"#EAEBEB"

```


```{r select-parameter, echo = FALSE}

source("../notebooks/r_utils.R")

cases <- prep_county(us_county, params$county, params$start_date)

hospitalizations <-prep_hospital(ca_hospitalizations, params$county, params$start_date)

```


## `r {params$county}` County: New Cases

```{r plot-cases, echo=FALSE}
source("../notebooks/r_chart_utils.R")

#https://stackoverflow.com/questions/38733403/edit-labels-in-tooltip-for-plotly-maps-using-ggplot2-in-r
cases_html<-plotCasesHTML(cases, 
                chart_title="New Cases: 7-day avg")

cases_html %>% ggplotly(
  tooltip=c("date", "new_cases_avg7")
)
```


## `r {params$county}` County: New Deaths

```{r plot-deaths, echo=FALSE}

deaths_html<-plotDeathsHTML(cases, 
                chart_title="New Deaths: 7-day avg")

deaths_html %>% ggplotly(
  tooltip=c("date", "new_deaths_avg7")
)
```